In [2]:
import numpy as np

In [8]:
# Define a matrix (2x3)
A = np.array(
    [
        [1.5, 2.9, 3.3],
        [4.7, 5.6, 6.2],
    ]
)
# Define a matrix (3x2)
A_T = A.transpose()

# Define a vector (3,)
xx1 = np.array([1.5, -6.6, 1.1])
xx2 = np.array([2.3, 6.7])

# Perform matrix-vector multiplication
yy1 = np.dot(A, xx1)
yy2 = np.dot(A_T, xx2)


print("Matrix:")
print(A)
print("Matrix - array form:")
print(A.ravel(order="F"))
print("\nVector:")
print(xx1)
print("\nResult of multiplication:")
print(yy1)

print()

print("Transposed Matrix:")
print(A_T)
print("Matrix - array form:")
print(A_T.ravel(order="F"))
print("\nVector:")
print(xx2)
print("\nResult of multiplication:")
print(yy2)

Matrix:
[[1.5 2.9 3.3]
 [4.7 5.6 6.2]]
Matrix - array form:
[1.5 4.7 2.9 5.6 3.3 6.2]

Vector:
[ 1.5 -6.6  1.1]

Result of multiplication:
[-13.26 -23.09]

Transposed Matrix:
[[1.5 4.7]
 [2.9 5.6]
 [3.3 6.2]]
Matrix - array form:
[1.5 2.9 3.3 4.7 5.6 6.2]

Vector:
[2.3 6.7]

Result of multiplication:
[34.94 44.19 49.13]


In [9]:
# Define a vector (3,)
xx2 = 3.0 * np.array([2.3, 6.7])

# Perform matrix-vector multiplication
yy2 = np.dot(A_T, xx2)


print("Transposed Matrix with scaled vector and matrix:")
print(A_T)
print("Matrix - array form:")
print(A_T.ravel(order="F"))
print("\nVector:")
print(xx2)
print("\nResult of multiplication:")
print(yy2)

Transposed Matrix with scaled vector and matrix:
[[1.5 4.7]
 [2.9 5.6]
 [3.3 6.2]]
Matrix - array form:
[1.5 2.9 3.3 4.7 5.6 6.2]

Vector:
[ 6.9 20.1]

Result of multiplication:
[104.82 132.57 147.39]
