In [1]:
import numpy as np

In [10]:
# Define a matrix (2x3)
matrix = np.array([[1.5, 2.9, 3.3], [4.7, 5.6, 6.2]])

# Define a vector (3,)
vector = np.array([1.5, -6.6, 1.1])

# Perform matrix-vector multiplication
result = np.dot(matrix, vector)

print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nResult of multiplication:")
print(result)

Matrix:
[[1.5 2.9 3.3]
 [4.7 5.6 6.2]]

Vector:
[ 1.5 -6.6  1.1]

Result of multiplication:
[-13.26 -23.09]
